// Load the .env file if it exists
require("dotenv").config();
const { BlobServiceClient } = require("@azure/storage-blob");

const { createWriteStream } = require("fs");
const { SitemapStream } = require("sitemap");

function excluder(filename) {
  if (filename.includes("reference-materials/6-4")) {
    return false;
  } else if (filename.includes("reference-materials/6-5")) {
    return false;
  } else if (filename.includes("reference-materials/cloud-service")) {
    return false;
  } else if (filename.includes("reference-materials/spec")) {
    return false;
  } else if (filename.includes("404")) {
    return false;
  } else {
    return true;
  }
}

async function main() {
  const connectionString = process.env.CONNECTION_STRING || "";
  const containerName = "$web";

  console.log("Running");

  const blobServiceClient = await BlobServiceClient.fromConnectionString(
    connectionString
  );
  const containerService = blobServiceClient.getContainerClient(containerName);

  let links = [];
  for await (const blob of containerService.listBlobsFlat()) {
    // exclude aem reference materials and 404 pages
    if (excluder(blob.name)) {
      if (blob.name.endsWith(".html") || blob.name.endsWith(".htm")) {
        // console.log(blob.name);
        const link = blob.name
          .replace("index.html", "")
          .replace("index.htm", "");

        if (notfoundlinks.includes(link)) {
          // console.log(link, "skipped");
        } else {
          links.push(link);
        }
      }
    }
  }
  links.forEach((link) => console.log(`https://developer.adobe.com/${link}`));
  // Create a stream to write to
  const sitemap = new SitemapStream({
    hostname: "https://developer.adobe.com/",
  });
  const writeStream = createWriteStream("./sitemap.xml");
  sitemap.pipe(writeStream);

  links.forEach((link) => {
    const linkObj = { url: link, changefreq: "monthly", priority: 0.7 };
    // console.log(linkObj);
    sitemap.write(linkObj);
  });
  sitemap.end();
}

main();

const notfoundlinks = [
  "purge-test/guides/",
  "uxp/docs/reference-js/Global Members/Data Transfers/fetch/",
  "uxp/xd/uxp/reference-css/Styles/visibility/",
  "uxp/xd/uxp/reference-css/Styles/margin/",
  "uxp/xd/develop/reference/interactions/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/",
  "uxp/xd/develop/tutorials/how-to-read-a-file/",
  "uxp/xd/develop/reference/ui/panels/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/domains/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-menu/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/BaseUIEvent/",
  "uxp/xd/uxp/reference-css/Selectors/Adjacent Sibling combinator/",
  "uxp/xd/design/",
  "uxp/xd/uxp/reference-css/Styles/border-style/",
  "uxp/xd/uxp/reference-css/Styles/overflow-x/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/GestureEvent/",
  "uxp/docs/uxp/reference-js/Modules/shell/Shell/",
  "uxp/docs/reference-js/Modules/os/",
  "uxp/xd/uxp/reference-css/Styles/flex-shrink/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Host Information/",
  "uxp/docs/uxp/reference-js/Global Members/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Enums/domains/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Classes/Entry/",
  "uxp/xd/develop/plugin-development/",
  "uxp/xd/develop/reference/uxp/module/storage/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/ProgressEvent/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Entry Points/",
  "uxp/xd/develop/reference/uxp/function/setInterval/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLStyleElement/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLInputElement/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-link/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLMenuItemElement/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Entry Points/UxpMenuItem/",
  "uxp/xd/uxp/reference-css/Styles/border-right-width/",
  "uxp/xd/uxp/reference-css/Selectors/Descendant combinator/",
  "uxp/docs/guides/reporting_api/reporting_breakdowns/",
  "uxp/docs/reference-js/Modules/uxp/Host Information/",
  "uxp/xd/uxp/reference-html/Hierarchy/footer/",
  "uxp/xd/develop/reference/uxp/class/HTMLDialogElement/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/empty/",
  "uxp/xd/uxp/Modules/uxp/Host Information/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLImageElement/",
  "purge-test/guides/jwt_authentication/",
  "uxp/xd/uxp/reference-css/Selectors/Class selector/",
  "aio-template-registry/reference/api/",
  "uxp/xd/uxp/Global Members/HTML Events/EventTarget/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/KeyboardEvent/",
  "uxp/xd/develop/reference/uxp/class/HTMLLabelElement/",
  "uxp/xd/develop/reference/uxp/class/ErrorEvent/",
  "uxp/xd/develop/reference/uxp/class/CSSStyleDeclaration/",
  "uxp/xd/develop/tutorials/quick-start-panel/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/File/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLLabelElement/",
  "uxp/xd/design/ux-patterns/messaging/",
  "uxp/xd/design/ux-patterns/branding/",
  "uxp/docs/uxp/reference-js/",
  "uxp/docs/uxp/reference-js/Global Members/Data Transfers/WebSocket/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Key-Value Storage/",
  "uxp/xd/develop/plugin-development/plugin-structure/manifest-v3/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLLinkElement/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/checked/",
  "uxp/xd/uxp/Modules/uxp/Key-Value Storage/",
  "uxp/xd/uxp/reference-css/Styles/background-repeat/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/localFileSystem/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/EntryMetadata/",
  "uxp/xd/uxp/reference-css/Styles/border-top/",
  "uxp/xd/develop/plugin-development/plugin-structure/",
  "uxp/xd/uxp/Modules/uxp/Entry Points/EntryPoints/",
  "uxp/xd/uxp/reference-js/Modules/shell/Shell/",
  "purge-test/guides/calculated_metrics_api/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLOptionElement/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/",
  "uxp/xd/develop/reference/uxp/class/DragEvent/",
  "uxp/xd/uxp/reference-css/Styles/background/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/Attr/",
  "uxp/xd/uxp/Global Members/HTML DOM/Document/",
  "uxp/xd/develop/reference/uxp/class/HTMLFormElement/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/NodeList/",
  "uxp/xd/develop/plugin-development/devtool/",
  "uxp/docs/concepts/",
  "uxp/xd/uxp/reference-css/Styles/padding-top/",
  "purge-test/guides/creating_oauth_client/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLInputElement/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/EventTarget/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLMenuItemElement/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLElement/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLHeadElement/",
  "uxp/docs/reference-js/Global Members/HTML DOM/",
  "uxp/docs/reference-js/Modules/uxp/Versions/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLAnchorElement/",
  "uxp/xd/develop/tutorials/how-to-show-an-alert/",
  "uxp/xd/uxp/reference-css/Styles/margin-right/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/Folder/",
  "uxp/xd/develop/reference/uxp/class/HTMLButtonElement/",
  "uxp/docs/reference-js/Global Members/HTML DOM/CharacterData/",
  "uxp/xd/uxp/Global Members/HTML Events/ProgressEvent/",
  "uxp/xd/develop/reference/uxp/class/CSSMediaList/",
  "uxp/xd/uxp/Global Members/HTML DOM/CharacterData/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/ClassList/",
  "uxp/xd/develop/reference/ui/panels/update/",
  "express-embed-sdk/docs/guides/ccx_editor/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/DragEvent/",
  "uxp/xd/develop/reference/uxp/function/fetch/",
  "uxp/xd/uxp/reference-css/Styles/align-items/",
  "aio-template-registry/",
  "uxp/xd/uxp/reference-css/Styles/bottom/",
  "uxp/xd/uxp/Global Members/HTML Events/DragEvent/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/types/",
  "uxp/xd/uxp/reference-spectrum/Typography/sp-detail/",
  "uxp/xd/uxp/reference-css/Styles/margin-left/",
  "uxp/xd/develop/reference/uxp/class/NodeList/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/MessageEvent/",
  "express-embed-sdk/docs/guides/changelog/",
  "uxp/xd/uxp/reference-css/Pseudo-elements/after/",
  "uxp/xd/develop/reference/uxp/class/HTMLAnchorElement/",
  "uxp/docs/reference-js/Modules/uxp/Entrypoints/",
  "uxp/docs/reference-js/",
  "aio-template-registry/reference/",
  "aio-template-registry/reference/cli/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/HTMLCollection/",
  "uxp/xd/uxp/reference-css/Styles/white-space/",
  "uxp/docs/reference-js/Global Members/HTML Events/",
  "uxp/xd/develop/plugin-development/devbestpractices/3-network-io/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/File/",
  "uxp/xd/develop/plugin-development/xd-concepts/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/NodeList/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/errors/",
  "uxp/xd/uxp/reference-spectrum/",
  "uxp/xd/develop/reference/ui/dialogs/dismissal/",
  "uxp/xd/develop/reference/uxp/class/HTMLCollection/",
  "uxp/xd/develop/reference/uxp/class/HTMLImageElement/",
  "uxp/xd/uxp/Global Members/Data Transfers/XMLHttpRequest/",
  "uxp/xd/develop/tutorials/content-index/",
  "uxp/xd/uxp/reference-js/Global Members/Data Transfers/fetch/",
  "uxp/xd/develop/reference/reference-index/",
  "uxp/xd/uxp/reference-css/Selectors/Attribute selector/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-divider/",
  "uxp/docs/reference-js/Global Members/HTML DOM/HTMLCollection/",
  "uxp/xd/uxp/reference-html/Hierarchy/h5/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLHtmlElement/",
  "uxp/xd/uxp/reference-css/Styles/display/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Host Information/",
  "uxp/xd/uxp/reference-css/Styles/margin-top/",
  "uxp/xd/uxp/reference-html/Hierarchy/h1/",
  "uxp/xd/develop/tutorials/how-to-integrate-with-OAuth/",
  "uxp/xd/uxp/Global Members/HTML DOM/DOMTokenList/",
  "uxp/xd/uxp/Global Members/Data Storage/",
  "uxp/xd/develop/reference/uxp/ui-classes-index/",
  "uxp/docs/uxp/reference-js/Modules/",
  "uxp/docs/reference-js/Modules/uxp/Key-Value Storage/localStorage/",
  "uxp/docs/guides/calculated_metrics_api/",
  "uxp/xd/develop/reference/Shadow/",
  "uxp/xd/develop/",
  "uxp/xd/develop/plugin-development/devtool/plugin-workflows/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/File/",
  "lightroom/",
  "uxp/xd/distribution/marketing/",
  "uxp/xd/develop/plugin-development/xd-concepts/automatic-cleanups/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLElement/",
  "uxp/xd/uxp/reference-css/Styles/margin-bottom/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/Entry/",
  "uxp/xd/develop/reference/uxp/class/UXPContainer/",
  "uxp/docs/reference-js/Global Members/Data Transfers/WebSocket/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/BaseUIEvent/",
  "uxp/xd/distribution/deep-links/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLDialogElement/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-slider/",
  "uxp/xd/uxp/Global Members/HTML DOM/Text/",
  "uxp/xd/develop/plugin-development/devtool/installation/",
  "uxp/docs/guides/segments_api/",
  "uxp/xd/uxp/reference-css/Styles/overflow-y/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/CharacterData/",
  "uxp/docs/uxp/reference-js/Global Members/Data Storage/LocalStorage/",
  "uxp/xd/develop/tutorials/how-to-style-text/",
  "uxp/docs/reference-js/Global Members/HTML DOM/DOMTokenList/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLLabelElement/",
  "uxp/xd/develop/plugin-development/devbestpractices/intro/",
  "uxp/xd/develop/plugin-development/plugin-structure/location/",
  "uxp/xd/uxp/reference-js/Global Members/Data Transfers/",
  "purge-test/guides/reporting_api/reporting_tips_tricks/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/PointerEvent/",
  "uxp/docs/reference-js/Modules/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLBodyElement/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLMenuElement/",
  "uxp/xd/develop/reference/Matrix/",
  "uxp/xd/uxp/reference-js/Global Members/Data Storage/LocalStorage/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/Element/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Entry Points/UxpMenuItems/",
  "uxp/docs/guides/reporting_api/reporting_breakdowns/reporting_multiple_breakdowns/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/nth-child/",
  "express-embed-sdk/docs/guides/",
  "express-embed-sdk/docs/guides/ccx_editor/customization/",
  "uxp/xd/develop/reference/uxp/network-index/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/NamedNodeMap/",
  "undefined/",
  "uxp/xd/uxp/reference-js/Global Members/Data Storage/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLProgressElement/",
  "uxp/xd/develop/reference/uxp/function/cancelAnimationFrame/",
  "uxp/xd/uxp/reference-js/Global Members/Data Transfers/XMLHttpRequest/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/nth-last-child/",
  "uxp/xd/develop/plugin-development/plugin-structure/handlers/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/MessageEvent/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/localFileSystem/",
  "uxp/xd/uxp/reference-css/Styles/letter-spacing/",
  "uxp/xd/uxp/reference-css/Styles/background-size/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/formats/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLImageElement/",
  "uxp/xd/uxp/reference-css/Pseudo-elements/",
  "uxp/docs/guides/oauth_using_curl/",
  "uxp/xd/design/ux-patterns/navigation/",
  "uxp/xd/develop/reference/uxp/class/XMLHttpRequest/",
  "uxp/xd/uxp/reference-css/Styles/flex-basis/",
  "uxp/xd/uxp/reference-css/Styles/border-bottom-style/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLDialogElement/",
  "uxp/xd/develop/plugin-development/xd-concepts/coordinate-spaces-and-units/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Classes/File/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLAnchorElement/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/DocumentFragment/",
  "uxp/docs/reference-js/Modules/shell/",
  "uxp/docs/reference-js/Global Members/HTML Events/GestureEvent/",
  "uxp/xd/develop/reference/uxp/function/clearInterval/",
  "uxp/xd/uxp/Modules/",
  "uxp/xd/uxp/reference-html/General/link/",
  "uxp/xd/uxp/reference-css/Styles/opacity/",
  "express-embed-sdk/docs/reference/ccx_editor/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-button/",
  "uxp/xd/develop/plugin-development/plugin-structure/menu-structure/",
  "uxp/xd/develop/reference/uxp/class/Document/",
  "uxp/docs/support/FAQ/",
  "uxp/xd/uxp/Global Members/HTML Events/KeyboardEvent/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/Text/",
  "uxp/xd/develop/reference/uxp/class/Clipboard/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Versions/Versions/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLDialogElement/",
  "uxp/xd/distribution/submission-checklist/",
  "uxp/xd/uxp/reference-css/General/calc/",
  "uxp/xd/uxp/Global Members/HTML DOM/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLDialogElement/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/domains/",
  "uxp/xd/community/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/hover/",
  "uxp/docs/support/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/modes/",
  "uxp/xd/develop/plugin-development/javascript-and-xd/javascript-support/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/nth-last-of-type/",
  "uxp/xd/develop/reference/uxp/class/WebSocket/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLAnchorElement/",
  "uxp/xd/uxp/reference-css/Styles/flex-grow/",
  "uxp/xd/uxp/Global Members/Data Storage/SessionStorage/",
  "express-embed-sdk/docs/guides/ccx_editor/edit_project/",
  "uxp/xd/uxp/Modules/os/",
  "uxp/xd/distribution/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/CharacterData/",
  "uxp/xd/develop/reference/ui/panels/hide/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLButtonElement/",
  "uxp/xd/develop/reference/uxp/class/Shell/",
  "uxp/xd/develop/reference/uxp/class/HTMLScriptElement/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Enums/modes/",
  "uxp/xd/uxp/reference-css/Styles/border-bottom-right-radius/",
  "uxp/xd/develop/reference/uxp/class/HTMLHeadElement/",
  "uxp/xd/uxp/Global Members/HTML DOM/Comment/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/NamedNodeMap/",
  "uxp/docs/uxp/reference-js/Global Members/Data Transfers/Clipboard/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/fileTypes/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/enabled/",
  "uxp/xd/uxp/reference-css/Styles/align-content/",
  "uxp/xd/uxp/reference-css/Styles/border-left-width/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLHtmlElement/",
  "uxp/xd/develop/reference/ui/",
  "uxp/xd/develop/reference/uxp/ui-index/",
  "uxp/xd/develop/reference/uxp/class/PointerEvent/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Key-Value Storage/SecureStorage/",
  "uxp/xd/uxp/reference-css/Styles/flex/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/",
  "purge-test/guides/oauth_using_curl/",
  "uxp/xd/design/ux-patterns/panel-ux/",
  "uxp/docs/reference-js/Modules/uxp/Key-Value Storage/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLHeadElement/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-checkbox/",
  "uxp/xd/uxp/reference-css/Styles/min-width/",
  "uxp/xd/develop/reference/uxp/class/FocusEvent/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/formats/",
  "uxp/xd/uxp/reference-js/Global Members/Data Storage/SessionStorage/",
  "purge-test/guides/reporting_api/reporting_breakdowns/reporting_multiple_breakdowns/",
  "express-embed-sdk/docs/guides/quick_actions/video/",
  "uxp/xd/uxp/reference-css/Styles/border-bottom-width/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Key-Value Storage/",
  "uxp/xd/uxp/reference-css/Media Queries/height/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/",
  "uxp/xd/uxp/reference-css/Styles/font-weight/",
  "uxp/xd/develop/tutorials/how-to-work-with-scenenodelist/",
  "uxp/xd/uxp/Global Members/HTML DOM/Node/",
  "purge-test/guides/reporting_api/reporting_breakdowns/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/EntryMetadata/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/ErrorEvent/",
  "uxp/xd/develop/reference/uxp/class/HTMLBodyElement/",
  "uxp/xd/uxp/reference-html/General/head/",
  "uxp/xd/develop/reference/uxp/class/CSSStyleSheet/",
  "uxp/xd/uxp/Global Members/HTML Events/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/Text/",
  "uxp/xd/develop/reference/uxp/class/Text/",
  "uxp/docs/reference-js/Global Members/Data Transfers/XMLHttpRequest/",
  "uxp/xd/uxp/reference-spectrum/User Interface/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/",
  "uxp/xd/develop/reference/uxp/class/HTMLElement/",
  "uxp/xd/develop/reference/uxp/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Entry Points/UxpMenuItems/",
  "uxp/xd/develop/reference/cloud/",
  "uxp/xd/develop/reference/uxp/module/shell/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/only-child/",
  "uxp/xd/uxp/reference-spectrum/Overview/About Spectrum UXP/",
  "uxp/xd/develop/plugin-development/devbestpractices/1-performance/",
  "express-embed-sdk/docs/guides/quick_actions/image/",
  "uxp/xd/uxp/Global Members/HTML Events/MessageEvent/",
  "express-embed-sdk/docs/reference/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/KeyboardEvent/",
  "uxp/xd/uxp/reference-spectrum/Typography/sp-body/",
  "uxp/xd/uxp/reference-css/Styles/border-left-style/",
  "uxp/xd/uxp/Modules/uxp/Entry Points/UxpMenuItem/",
  "uxp/xd/uxp/reference-css/Styles/border-left/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/active/",
  "uxp/xd/develop/reference/uxp/class/StyleSheet/",
  "uxp/xd/uxp/reference-html/Hierarchy/h6/",
  "uxp/xd/uxp/reference-css/Styles/background-image/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/DOMTokenList/",
  "uxp/docs/reference-js/Global Members/HTML DOM/Attr/",
  "uxp/xd/develop/reference/",
  "uxp/xd/uxp/reference-js/Modules/uxp/",
  "uxp/xd/uxp/reference-css/Styles/border-radius/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/localFileSystem/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLOptionElement/",
  "uxp/docs/reference-js/Modules/os/OS/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLHtmlElement/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/first-child/",
  "uxp/xd/develop/reference/uxp/events-index/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Enums/types/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLTextAreaElement/",
  "uxp/xd/uxp/reference-css/Styles/border-color/",
  "uxp/xd/develop/reference/uxp/class/EventTarget/",
  "uxp/xd/develop/reference/uxp/class/DOMTokenList/",
  "uxp/xd/develop/reference/scenegraph/",
  "uxp/xd/develop/plugin-development/javascript-and-xd/environment/",
  "uxp/xd/develop/tutorials/ui-index/",
  "uxp/xd/uxp/reference-html/General/style/",
  "uxp/docs/reference-js/Global Members/Data Transfers/Clipboard/",
  "uxp/xd/uxp/Modules/os/OS/",
  "uxp/xd/uxp/reference-css/Selectors/Type selector/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/domains/",
  "uxp/xd/develop/reference/uxp/class/CharacterData/",
  "express-embed-sdk/docs/support/",
  "uxp/docs/reference-js/Global Members/HTML DOM/DocumentFragment/",
  "uxp/xd/uxp/reference-css/Styles/border-right/",
  "uxp/docs/reference-js/Global Members/HTML Events/CloseEvent/",
  "uxp/xd/develop/reference/Blur/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/modes/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Entry Points/UxpPluginInfo/",
  "uxp/xd/develop/reference/commands/",
  "uxp/xd/uxp/Modules/uxp/Entry Points/EntryPointsError/",
  "uxp/xd/distribution/distribution-options/",
  "uxp/xd/develop/reference/uxp/module/uxp/",
  "uxp/xd/uxp/reference-spectrum/Typography/sp-label/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLScriptElement/",
  "uxp/xd/uxp/reference-css/Selectors/Child combinator/",
  "uxp/docs/reference-js/Global Members/HTML Elements/",
  "purge-test/guides/segments_api/",
  "uxp/xd/uxp/Modules/shell/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/Comment/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLScriptElement/",
  "uxp/docs/guides/",
  "uxp/xd/uxp/reference-css/Styles/border-top-color/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/DOMTokenList/",
  "uxp/xd/develop/reference/uxp/class/WheelEvent/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLBodyElement/",
  "uxp/xd/uxp/reference-css/Styles/max-width/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLScriptElement/",
  "project-firefly/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Entry Points/UxpPluginInfo/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Enums/fileTypes/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLMenuElement/",
  "uxp/xd/uxp/Modules/uxp/Entry Points/UxpCommandInfo/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Host Information/Host/",
  "uxp/xd/uxp/reference-css/Styles/border-left-color/",
  "uxp/docs/guides/migrating/",
  "uxp/docs/uxp/reference-js/Global Members/Data Transfers/fetch/",
  "uxp/xd/develop/tutorials/quick-start/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/Node/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLTextAreaElement/",
  "uxp/docs/reference-js/Modules/uxp/Key-Value Storage/sessionStorage/",
  "uxp/xd/develop/plugin-development/xd-concepts/edit-context/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/focus/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/",
  "uxp/xd/uxp/Global Members/HTML Events/GestureEvent/",
  "uxp/xd/develop/reference/uxp/function/requestAnimationFrame/",
  "uxp/xd/uxp/reference-css/General/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/Element/",
  "uxp/xd/uxp/reference-css/Styles/top/",
  "aio-template-registry/api/",
  "uxp/docs/uxp/reference-js/Global Members/Data Transfers/XMLHttpRequest/",
  "express-embed-sdk/docs/guides/quick_actions/",
  "uxp/xd/uxp/Modules/shell/Shell/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLButtonElement/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/FileSystemProvider/",
  "uxp/xd/uxp/Global Members/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Entry Points/EntryPointsError/",
  "uxp/xd/uxp/reference-css/General/units/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLMenuElement/",
  "uxp/xd/uxp/reference-css/Styles/border-top-left-radius/",
  "purge-test/",
  "uxp/xd/develop/reference/uxp/class/HTMLStyleElement/",
  "uxp/xd/develop/plugin-development/xd-concepts/apis/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Entry Points/UxpPanelInfo/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/",
  "uxp/xd/uxp/reference-css/Styles/max-height/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLImageElement/",
  "uxp/xd/develop/reference/application/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLProgressElement/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLStyleElement/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLOptionElement/",
  "uxp/xd/uxp/Modules/uxp/Entry Points/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLSelectElement/",
  "uxp/docs/reference-js/Global Members/HTML Events/PointerEvent/",
  "uxp/docs/reference-js/Global Members/Data Transfers/",
  "uxp/xd/uxp/reference-css/Styles/border-top-width/",
  "uxp/xd/develop/reference/Color/",
  "uxp/xd/develop/reference/uxp/class/HTMLMenuItemElement/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/GestureEvent/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/ProgressEvent/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Enums/errors/",
  "uxp/xd/develop/reference/uxp/storage-index/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-dropdown/",
  "aio-template-registry/reference/github/",
  "uxp/xd/uxp/reference-css/Styles/left/",
  "purge-test/api/1.4/",
  "uxp/xd/uxp/reference-css/Styles/font-style/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/Comment/",
  "uxp/xd/uxp/reference-spectrum/Overview/Using with React/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-action-button/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-radio-group/",
  "uxp/xd/develop/reference/assets/",
  "express-embed-sdk/docs/guides/ccx_editor/create_project/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Entry Points/",
  "uxp/xd/uxp/reference-html/Hierarchy/h4/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLInputElement/",
  "uxp/xd/develop/plugin-development/javascript-and-xd/sync-async/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-textarea/",
  "uxp/xd/uxp/Modules/uxp/",
  "uxp/xd/develop/plugin-development/devbestpractices/",
  "uxp/docs/reference-js/Global Members/HTML Events/KeyboardEvent/",
  "uxp/xd/uxp/reference-css/Styles/height/",
  "uxp/xd/develop/tutorials/quick-start-react/",
  "uxp/docs/reference-js/Modules/uxp/Key-Value Storage/secureStorage/SecureStorage/",
  "uxp/xd/develop/plugin-development/devbestpractices/5-ui/",
  "uxp/xd/develop/reference/uxp/class/BaseUIEvent/",
  "uxp/xd/uxp/reference-html/General/script/",
  "uxp/xd/uxp/reference-css/Styles/padding-right/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/ErrorEvent/",
  "uxp/xd/uxp/reference-css/Styles/overflow/",
  "express-embed-sdk/docs/",
  "uxp/docs/reference-js/Global Members/HTML DOM/Comment/",
  "uxp/xd/develop/tutorials/",
  "uxp/docs/guides/jwt_authentication/",
  "uxp/xd/uxp/Global Members/HTML Events/CloseEvent/",
  "uxp/xd/distribution/packaging-your-plugin/",
  "uxp/xd/uxp/reference-css/Styles/padding-bottom/",
  "uxp/xd/uxp/reference-css/Media Queries/width/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/last-child/",
  "express-embed-sdk/docs/reference/quick_actions/",
  "uxp/xd/develop/plugin-development/devtool/plugin-management/",
  "uxp/xd/develop/reference/uxp/class/HTMLOptionElement/",
  "uxp/xd/develop/reference/uxp/class/HTMLMenuElement/",
  "uxp/xd/develop/reference/core-index/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/fileTypes/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-icon/",
  "uxp/docs/reference-js/Global Members/HTML DOM/Text/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLTextAreaElement/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLProgressElement/",
  "uxp/xd/uxp/reference-css/Styles/min-height/",
  "uxp/docs/reference-js/Global Members/HTML DOM/NodeList/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/disabled/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/root/",
  "purge-test/guides/reporting_api/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLInputElement/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLHtmlElement/",
  "uxp/docs/reference-js/Global Members/",
  "uxp/docs/uxp/reference-js/Modules/os/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Classes/",
  "uxp/xd/develop/plugin-development/devbestpractices/4-file-io/",
  "uxp/docs/uxp/reference-js/Modules/uxp/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLSelectElement/",
  "uxp/xd/uxp/reference-css/Styles/text-align/",
  "uxp/xd/develop/reference/selection/",
  "uxp/xd/uxp/reference-css/Selectors/Identifier selector/",
  "uxp/docs/guides/creating_oauth_client/",
  "uxp/xd/develop/reference/LinearGradientFill/",
  "uxp/docs/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/FileSystemProvider/",
  "uxp/xd/uxp/reference-css/",
  "uxp/xd/develop/reference/uxp/class/CSSMediaRule/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLSelectElement/",
  "uxp/docs/reference-js/Global Members/HTML DOM/NamedNodeMap/",
  "uxp/xd/uxp/Global Members/HTML Events/BaseUIEvent/",
  "uxp/docs/reference-js/Global Members/HTML Events/Event/",
  "uxp/xd/uxp/reference-js/Global Members/Data Transfers/Clipboard/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/FileSystemProvider/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Entry Points/EntryPoints/",
  "uxp/xd/develop/reference/xd-index/",
  "uxp/xd/uxp/reference-css/Styles/background-attachment/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLImageElement/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Key-Value Storage/SecureStorage/",
  "uxp/xd/develop/reference/clipboard/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/Event/",
  "uxp/xd/develop/tutorials/how-to-create-paths/",
  "uxp/xd/develop/reference/uxp/function/setTimeout/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLBodyElement/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Instances/localFileSystem/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLMenuElement/",
  "uxp/docs/uxp/reference-js/Global Members/Data Storage/SessionStorage/",
  "uxp/xd/develop/reference/uxp/class/Node/",
  "uxp/xd/develop/reference/uxp/class/HTMLSelectElement/",
  "uxp/xd/uxp/reference-js/Modules/os/",
  "uxp/xd/uxp/reference-css/Styles/",
  "uxp/xd/develop/reference/uxp/class/Event/",
  "uxp/xd/develop/plugin-development/devbestpractices/2-scenegraph/",
  "uxp/xd/uxp/Global Members/Data Storage/LocalStorage/",
  "uxp/xd/develop/known-issues/",
  "uxp/docs/reference-js/Global Members/HTML Events/EventTarget/",
  "uxp/xd/uxp/reference-html/",
  "uxp/xd/uxp/Global Members/Data Transfers/Clipboard/",
  "purge-test/support/contribute/",
  "uxp/xd/design/ux-patterns/modal-ux/",
  "uxp/xd/develop/reference/uxp/class/KeyboardEvent/",
  "uxp/xd/uxp/reference-css/Styles/border-width/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-progressbar/",
  "uxp/xd/uxp/reference-js/Global Members/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLStyleElement/",
  "uxp/xd/uxp/reference-spectrum/Overview/",
  "uxp/xd/uxp/Modules/uxp/Entry Points/UxpMenuItems/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLMenuItemElement/",
  "uxp/xd/uxp/reference-js/Modules/shell/",
  "uxp/xd/uxp/reference-css/Styles/font-family/",
  "uxp/xd/develop/reference/uxp/class/HTMLHtmlElement/",
  "uxp/docs/guides/discovery_api/",
  "express-embed-sdk/docs/guides/authorization/",
  "uxp/xd/uxp/reference-css/Media Queries/prefers-color-scheme/",
  "uxp/xd/develop/reference/uxp/class/Image/",
  "uxp/xd/develop/tutorials/io-index/",
  "uxp/xd/develop/reference/uxp/class/CloseEvent/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLButtonElement/",
  "uxp/xd/develop/reference/ui/dialogs/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/DocumentFragment/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/HTMLCollection/",
  "uxp/docs/uxp/reference-js/Global Members/HTML DOM/Document/",
  "uxp/xd/uxp/reference-html/General/Unsupported Attributes/",
  "uxp/xd/uxp/Modules/uxp/Versions/",
  "uxp/xd/uxp/reference-css/Styles/font-size/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-textfield/",
  "uxp/xd/design/ux-patterns/onboarding/",
  "uxp/xd/develop/plugin-development/plugin-structure/manifest/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLAnchorElement/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Versions/",
  "uxp/xd/develop/reference/uxp/class/HTMLInputElement/",
  "uxp/xd/develop/reference/uxp/class/StyleSheetList/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/Folder/",
  "uxp/docs/reference-js/Modules/uxp/Host Information/Host/",
  "uxp/docs/support/contribute/",
  "uxp/xd/develop/plugin-development/xd-concepts/scenegraph/",
  "uxp/xd/develop/reference/uxp/class/Element/",
  "uxp/xd/uxp/reference-html/General/body/",
  "uxp/xd/develop/reference/uxp/class/FormData/",
  "uxp/docs/reference-js/Modules/shell/Shell/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Entry Points/UxpCommandInfo/",
  "uxp/xd/uxp/reference-css/Styles/padding-left/",
  "uxp/xd/uxp/Global Members/HTML Events/PointerEvent/",
  "uxp/docs/uxp/reference-js/Modules/shell/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/Folder/",
  "purge-test/guides/migrating/",
  "uxp/xd/uxp/Global Members/HTML DOM/NamedNodeMap/",
  "uxp/xd/develop/reference/uxp/class/Performance/",
  "uxp/docs/reference-js/Global Members/HTML DOM/ClassList/",
  "uxp/xd/uxp/reference-css/Styles/background-color/",
  "uxp/xd/develop/reference/uxp/class/Console/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLLinkElement/",
  "uxp/xd/uxp/",
  "uxp/xd/uxp/Global Members/HTML DOM/HTMLCollection/",
  "uxp/xd/uxp/Global Members/HTML Events/Event/",
  "uxp/docs/api/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLLinkElement/",
  "uxp/xd/develop/reference/uxp/class/Navigator/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLLinkElement/",
  "uxp/xd/develop/changelog/",
  "uxp/xd/uxp/reference-html/Hierarchy/h2/",
  "uxp/xd/develop/reference/uxp/class/Location/",
  "uxp/xd/develop/reference/uxp/class/NamedNodeMap/",
  "uxp/xd/develop/tutorials/debugging/",
  "uxp/xd/uxp/Global Members/HTML DOM/ClassList/",
  "uxp/xd/uxp/reference-css/Styles/border-bottom/",
  "uxp/xd/develop/reference/uxp/class/ClassList/",
  "uxp/docs/reference-js/Global Members/HTML Events/ErrorEvent/",
  "uxp/docs/reference-js/Modules/uxp/",
  "uxp/xd/develop/reference/ui/panels/show/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/nth-of-type/",
  "uxp/xd/uxp/reference-css/Styles/right/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/ClassList/",
  "uxp/xd/develop/reference/uxp/class/CSSGroupingRule/",
  "uxp/xd/develop/reference/uxp/class/HTMLProgressElement/",
  "aio-template-registry/guides/",
  "uxp/docs/reference-js/Global Members/HTML DOM/Node/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLSelectElement/",
  "purge-test/support/FAQ/",
  "uxp/xd/develop/reference/ui/dialogs/showing/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLHeadElement/",
  "uxp/xd/develop/reference/uxp/class/HTMLLinkElement/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-menu-item/",
  "uxp/xd/develop/reference/uxp/class/CSSStyleRule/",
  "uxp/docs/reference-js/Modules/uxp/Key-Value Storage/secureStorage/",
  "uxp/xd/uxp/reference-css/Styles/border-bottom-left-radius/",
  "uxp/xd/uxp/reference-html/Hierarchy/h3/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/types/",
  "uxp/xd/uxp/reference-spectrum/Typography/",
  "uxp/xd/uxp/Global Members/HTML DOM/DocumentFragment/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/errors/",
  "uxp/docs/uxp/reference-js/Global Members/Data Storage/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLStyleElement/",
  "purge-test/guides/discovery_api/",
  "uxp/xd/develop/plugin-development/xd-concepts/lifecycle/",
  "uxp/xd/uxp/reference-css/Selectors/",
  "uxp/docs/reference-js/Global Members/HTML Events/ProgressEvent/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLMenuItemElement/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/modes/",
  "uxp/xd/uxp/Modules/uxp/Entry Points/UxpPanelInfo/",
  "uxp/xd/uxp/Global Members/HTML Events/ErrorEvent/",
  "uxp/xd/uxp/reference-css/General/variables/",
  "uxp/xd/uxp/Modules/uxp/Entry Points/UxpPluginInfo/",
  "uxp/xd/uxp/reference-css/Selectors/Universal selector/",
  "uxp/xd/develop/reference/uxp/class/HTMLTextAreaElement/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Versions/",
  "uxp/xd/develop/reference/uxp/class/Blob/",
  "uxp/xd/uxp/reference-js/Modules/",
  "uxp/xd/develop/reference/uxp/class/ProgressEvent/",
  "uxp/xd/develop/tutorials/how-to-export-a-rendition/",
  "uxp/docs/guides/reporting_api/reporting_tips_tricks/",
  "uxp/docs/reference-js/Global Members/HTML Events/DragEvent/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLElement/",
  "uxp/xd/develop/tutorials/how-to-ask-user-for-confirmation/",
  "uxp/docs/reference-js/Global Members/HTML Events/BaseUIEvent/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Instances/",
  "uxp/xd/uxp/reference-css/Styles/padding/",
  "uxp/xd/uxp/Modules/uxp/Key-Value Storage/SecureStorage/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Enums/formats/",
  "uxp/xd/uxp/Modules/uxp/Versions/Versions/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Entry Points/UxpCommandInfo/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLOptionElement/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/formats/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/EventTarget/",
  "uxp/xd/uxp/reference-html/Hierarchy/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Entry Points/UxpPanelInfo/",
  "uxp/xd/develop/plugin-development/xd-concepts/properties-with-object-values/",
  "uxp/xd/develop/reference/uxp/module/os/",
  "uxp/docs/reference-js/Global Members/HTML DOM/Element/",
  "uxp/xd/develop/reference/uxp/class/DOMException/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/",
  "uxp/xd/uxp/Modules/uxp/Host Information/Host/",
  "uxp/xd/uxp/Global Members/HTML DOM/NodeList/",
  "uxp/xd/develop/reference/uxp/class/CSSRule/",
  "uxp/xd/develop/reference/uxp/class/MessageEvent/",
  "uxp/xd/develop/reference/uxp/function/clearTimeout/",
  "uxp/xd/uxp/reference-spectrum/Typography/sp-heading/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Entry Points/EntryPoints/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Entry Points/EntryPointsError/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/EntryMetadata/",
  "uxp/xd/develop/plugin-development/devtool/working-with-react/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Classes/EntryMetadata/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Persistent File Storage/types/",
  "kits/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Events/CloseEvent/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Classes/Folder/",
  "uxp/docs/uxp/reference-js/Modules/os/OS/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/DragEvent/",
  "uxp/xd/develop/reference/uxp/class/OS/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLElement/",
  "uxp/xd/uxp/reference-js/",
  "uxp/xd/uxp/reference-css/Styles/border-right-style/",
  "uxp/xd/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Enums/",
  "uxp/xd/uxp/Global Members/HTML Elements/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLLabelElement/",
  "uxp/xd/develop/reference/SceneNodeList/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Entry Points/UxpMenuItem/",
  "purge-test/support/community/",
  "uxp/xd/develop/reference/PerPluginStorage/",
  "uxp/xd/uxp/reference-css/Styles/border-right-color/",
  "uxp/xd/develop/reference/uxp/class/CSSRuleList/",
  "uxp/xd/develop/tutorials/how-to-make-network-requests/",
  "uxp/xd/develop/reference/uxp/ui-html-index/",
  "uxp/xd/uxp/Global Members/Data Transfers/fetch/",
  "uxp/xd/develop/reference/uxp/class/DocumentFragment/",
  "uxp/xd/uxp/reference-css/Styles/align-self/",
  "uxp/xd/uxp/reference-js/Modules/uxp/Host Information/Host/",
  "uxp/xd/develop/reference/uxp/namespace/css/",
  "uxp/xd/develop/tutorials/how-to-draw-lines/",
  "uxp/xd/develop/reference/ImageFill/",
  "uxp/xd/uxp/Global Members/Data Transfers/",
  "uxp/xd/uxp/reference-css/Media Queries/",
  "uxp/docs/reference-js/Global Members/HTML Elements/HTMLScriptElement/",
  "uxp/xd/develop/reference/uxp/class/Comment/",
  "uxp/xd/uxp/reference-css/Pseudo-classes/",
  "uxp/docs/guides/reporting_api/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLLabelElement/",
  "express-embed-sdk/docs/guides/local/",
  "uxp/xd/uxp/reference-html/Hierarchy/hr/",
  "uxp/xd/uxp/reference-js/Modules/os/OS/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/Entry/",
  "uxp/xd/develop/reference/how-to-read/",
  "uxp/xd/design/user-interface/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/CloseEvent/",
  "uxp/xd/uxp/Global Members/HTML DOM/Element/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLHeadElement/",
  "uxp/docs/reference-js/Global Members/HTML Events/MessageEvent/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Versions/Versions/",
  "uxp/docs/uxp/reference-js/Global Members/HTML Elements/HTMLButtonElement/",
  "uxp/xd/uxp/reference-html/General/html/",
  "uxp/xd/uxp/reference-css/Styles/flex-direction/",
  "purge-test/support/",
  "uxp/xd/uxp/reference-css/Styles/flex-wrap/",
  "uxp/xd/uxp/Global Members/Data Transfers/WebSocket/",
  "uxp/xd/uxp/reference-css/Styles/text-overflow/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/Node/",
  "uxp/docs/guides/oauth_using_postman/",
  "aio-template-registry/guides/requirements/",
  "uxp/xd/uxp/reference-css/Styles/justify-content/",
  "uxp/xd/uxp/reference-css/Styles/border-bottom-color/",
  "uxp/xd/uxp/Global Members/HTML DOM/Attr/",
  "purge-test/api/",
  "uxp/xd/uxp/reference-css/Styles/border-top-style/",
  "uxp/xd/uxp/reference-css/Styles/color/",
  "uxp/xd/develop/plugin-development/plugin-structure/folder-structure/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/PointerEvent/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/Document/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLBodyElement/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/errors/",
  "uxp/xd/uxp/Modules/uxp/Persistent File Storage/Entry/",
  "uxp/xd/uxp/reference-css/Styles/width/",
  "uxp/docs/uxp/reference-js/Global Members/Data Transfers/",
  "uxp/docs/reference-js/Modules/uxp/Persistent File Storage/Classes/FileSystemProvider/",
  "aio-template-registry/guides/creating_template/",
  "uxp/xd/develop/reference/uxp/class/GestureEvent/",
  "express-embed-sdk/docs/reference/shared_types/",
  "purge-test/guides/oauth_using_postman/",
  "uxp/xd/design/ux-patterns/",
  "uxp/xd/uxp/reference-html/General/",
  "uxp/xd/uxp/reference-spectrum/User Interface/sp-radio/",
  "uxp/docs/uxp/reference-js/Modules/uxp/Persistent File Storage/fileTypes/",
  "uxp/xd/uxp/reference-html/General/Unsupported Elements/",
  "uxp/xd/uxp/reference-js/Global Members/HTML DOM/Attr/",
  "uxp/xd/develop/reference/uxp/class/Attr/",
  "uxp/xd/uxp/Global Members/HTML Elements/HTMLTextAreaElement/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Events/Event/",
  "uxp/xd/uxp/reference-css/Pseudo-elements/before/",
  "uxp/docs/reference-js/Global Members/HTML DOM/Document/",
  "uxp/xd/develop/plugin-development/javascript-and-xd/",
  "uxp/xd/uxp/reference-css/Selectors/General Sibling combinator/",
  "uxp/xd/uxp/reference-js/Global Members/Data Transfers/WebSocket/",
  "uxp/xd/develop/reference/viewport/",
  "uxp/docs/reference-js/Modules/uxp/Key-Value Storage/localStorage/LocalStorage/",
  "uxp/xd/uxp/reference-js/Global Members/HTML Elements/HTMLProgressElement/",
];
